[project]
name = "findcrypt-yara-x"
version = "0.1.0"
description = "YARA-X support for findcrypt idapython plugin"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "yara-x>=1.5.0",
]
